### ISSUE TITLE
Resolve Stdheprdr and stdheprdrnew

### ISSUE THREAD

**Issue by jstrube** [iLCSoft/LCIO#8]
Maybe it's just me, but I am confused by the fact that there are two implementations.
Are both really needed? If so, can one be renamed?

**Comment by gaede** [comment]
Jeremy has fixed an issue in Stdheprdr for the HPS in StdheprdrNew. As we are confident StdhepRdr worked for ILC and CLIC so far, I suggested to add the new one until we find the time to verify that the new one also works for LC. Volunteers for checking this are welcome ...

**Comment by JeremyMcCormick** [comment]
The issue was that the existing "old" reader only uses one set of the parent/daughter links and ignores the other.  This is obviously not correct in terms of the HEPEVT standard.  Certain StdHep files are processed completely incorrectly by the old reader.

Frank, I really think that as the original author of this reader class, you need to deal with trying to fix this up and verifying it including testing various StdHep files.  The current implementation is simply incomplete, and I don't think that a call for "volunteers" is really going to be adequate.  I did my own tests but you are going to need to jump in here and perform your own checks/tests or this is never going to get resolved.

If you need some sample files please let me know.

**Comment by jstrube** [comment]
@JeremyMcCormick Yes, please point us to some sample files.

**Comment by JeremyMcCormick** [comment]
Hi, Jan.

I may only have available stdhep files for fixed target experiments, rather than full ILC events, which I will try to post here via ftp when I have a chance.

Basically, any generator that relies on daughter to parent pointers (specified by two fields in the HEPEVT block) while not setting the corresponding parent to daughter links, will not be processed properly.

From what I remember the Madgraph4 and 5 generators produce files by default in which this is the case.

Again though will try to post some files when I have a chance...

**Comment by jstrube** [comment]
If you have some files where the new reader works, but the old one breaks, that would be good.
I have plenty of files that I know work with the old reader, so I can compare.

**Comment by rete** [comment]
Poping up some issues from hell. Is it fixed by now ? Should we close it ?

**Comment by jstrube** [comment]
Not fixed. Please pick one of the two implementations as default and remove the other one.
